#!/usr/bin/env bash
#
# Install Bats

set -e -o pipefail

# shellcheck disable=SC2223
: ${BATS_VERSION:='1.2.1'}
# shellcheck disable=SC2223
: ${BATS_SHA1SUM:='418ca60af55c339ac7911c74a44f7edf41e3a17c'}
# shellcheck disable=SC2223
: ${PREFIX:=/usr/local}
# shellcheck disable=SC2223
: ${SRCDIR:="${PREFIX}/src"}

if [[ "${PREFIX:0:1}" != '/' ]]; then
  echo "$(basename "${0}"): PREFIX must be an absolute path" >&2
  exit 1
fi

if [[ "${SRCDIR:0:1}" != '/' ]]; then
  echo "$(basename "${0}"): SRCDIR must be an absolute path" >&2
  exit 1
fi

if [[ -n "$(command -v sha1sum)" ]]; then
  sha1_prog='sha1sum -c'
elif [[ -n "$(command -v shasum)" ]]; then
  sha1_prog='shasum -a 1 -c'
else
  echo "$(basename "${0}"): No sha1 program found" >&2
  exit 1
fi

mkdir -p "${SRCDIR}"
cd "${SRCDIR}"
wget -nv "https://github.com/bats-core/bats-core/archive/v${BATS_VERSION}.tar.gz"
${sha1_prog} <<< "${BATS_SHA1SUM}  v${BATS_VERSION}.tar.gz"
tar -xf "v${BATS_VERSION}.tar.gz"
rm "v${BATS_VERSION}.tar.gz"
cd "bats-core-${BATS_VERSION}"

./install.sh "${PREFIX}"
